apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  namespace: team-a-dev
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["echo", "Pre-sync job running"]
      restartPolicy: Never
