apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base

helmCharts:
  - name: app1
    chartPath: ../../base
    valuesFile: values-dev.yaml