apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Usá esto si necesitás modificar recursos
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: my-app

# Opcional: etiquetas comunes si querés que todo lo que despliegue tenga una
labels:
  - pairs:
      app: my-app

helmCharts:
  - name: app1
    version: 0.1.0
    releaseName: app1
    valuesFile: values-dev.yaml