apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: app1
    releaseName: app1
    version: 0.1.0
    repo: file://../base/charts/app1/template
    valuesFile: values.yaml
