apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../base/charts

helmCharts:
  - name: app1
    releaseName: app1
    valuesFile: values/dev-values.yaml
    namespace: team-a

labels:
  - pairs:
      app: my-app