apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Usá esto si necesitás modificar recursos
patchesStrategicMerge:
  - patch.yaml

# Opcional: etiquetas comunes si querés que todo lo que despliegue tenga una
labels:
  - pairs:
      app: my-app