apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ["sh", "-c", "echo Inicializando..."]
      restartPolicy: Never
